### ISSUE TITLE
Crash on compiling

### ISSUE THREAD

**Issue by paolobolzoni** [be5invis/Sarasa-Gothic#134]
version: git `1103f343cbd14914a68a5cea5e390effe7abe14a` commit
Os version (`uname-a`): `Linux fww 5.5.1-arch1-1 #1 SMP PREEMPT Sat, 01 Feb 2020 16:38:40 +0000 x86_64 GNU/Linux`
Compiling programs versions:
```
$ node -v
v12.14.1
$ otfccbuild -v
This is otfccbuild, version 0.10.3.
$ otfccdump -v
This is otfccdump, version 0.10.3.
```

Error log
```
$ npm run build ttf                                                                                                                                                                                      [864/864]

> sarasa-gothic@0.11.0 build /var/second_home/iosevka/Sarasa-Gothic
> verda -f verdafile.js "ttf"

● Note Invalidating build journal due to self-tracking.
♦ otf2ttf -o build/shs/sc-extralight.tmp.ttf sources/shs/SourceHanSansSC-ExtraLight.otf
♦ otf2ttf -o build/shs/cl-extralight.tmp.ttf sources/shs/SourceHanSansK-ExtraLight.otf
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ufoProcessor 1.8 (/usr/lib/python3.8/site-packages), Requirement.parse('ufoProcessor<=1.0.6,>=1.0.5'), {'afdko'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/otf2ttf", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ufoProcessor<=1.0.6,>=1.0.5' distribution was not found and is required by afdko
× Error Unhandled exception when building "Builtin::File::build/shs/cl-extralight.otd":
 { code: 1 }
```

It appears one needs versions 1.0.5 or 1.0.6 of ufoProcessor. Is it the case? My ufoProcessor version is 1.8.

**Comment by Lemmingh** [comment]
The [dependencies of AFDKO 3.2.0](https://github.com/adobe-type-tools/afdko/blob/3.2.0/requirements.txt) were awkward. Its next release resolved the problem.
